### ISSUE TITLE
Scope subsets problems

### ISSUE THREAD

**Issue by jricher** [smart-on-fhir/auth-server#2]
From @michelemottini on https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/755
## 

My understanding is that the scopes defined here:
![image](https://cloud.githubusercontent.com/assets/313089/6090965/301a04fc-ae48-11e4-857b-0ca73411203f.png)

are all the possible scopes for the client app - and that the app specifies the actual scopes it needs as part of the authorization process - but if the app specifies `user/*.read` the server returns an invalid scope error (even if `user/*.read` is a subset of `user/*.*`)

**Comment by nschwertner** [comment]
The scopes that you are listing are missing the wildcard characters (i.e. should be `user/*.read`). This said, we haven't implemented any other user scopes than `user/*.*` at the moment. Which is not to say that we won't add them... right, Josh?

**Comment by jmandel** [comment]
Our [spec](http://docs.smartplatforms.org/authorization/scopes-and-launch-context/) does indeed define resource-specific scopes for any FHIR resource an app might want to access. But our auth server so far only includes `user/*.*` and `patient/*.read` by default. It's an oversight, and we can definitely add `user/*.read` and `patient/*.*` to the default list of options [scopes.sql](https://github.com/smart-on-fhir/auth-server/blob/1520cc73de55f152e83cbeb7fb74c87f6bba9159/openid-connect-server-webapp/src/main/resources/db/scopes.sql#L29).

(@nschwertner, the missing `*` was just a text formatting error that got introduce when @jricher copied the issue over from mitreid-connect/OpenID-Connect-Java-Spring-Server#755 ...)
